version: '3.3'
services:
  elasticsearch:
    image: bigdatagrapes/elasticsearch
    container_name: elasticsearch
    environment:
      - "192.168.1.77"
    ports:
      - 9200:9200
      - 9300:9300  
      
  kibana:
    image: bigdatagrapes/kibana
    container_name: kibana
    environment:
      - "192.168.1.77"
    ports:
      - 5601:5601

  hbase:
    image: bigdatagrapes/hbase
    container_name: hbase
    environment:
      - "192.16.1.77"
    ports:
      - 16000:16000
      - 16010:16010

      
  flink:
    image: bigdatagrapes/flink
    container_name: flink
    environment:
      - "192.168.1.77"
    ports:
      - 6123:6123
      - 8089:8089

  spark-master:
    image: bigdatagrapes/spark-master
    container_name: spark-master
    environment:
      - "192.168.1.77"
    ports:
      - 8080:8080
      - 6066:6066
      - 7077:7077

  spark-worker:
    image: bigdatagrapes/spark-worker
    container_name: spark-worker
    environment:
      - "192.168.1.77"
    ports:
      - 8081:8081

  mongo:
    image: bigdatagrapes/mongo
    container_name: mongo
    environment:
      - "192.168.1.77"
    ports:
      - 27017:27017

  sparklingwater:
    image: bigdatagrapes/sparklingwater
    container_name: sparklingwater
    environment:
      - "192.168.1.77"
    ports:
      - 27000:27017
      
  kafka:
    image: bigdatagrapes/kafka
    container_name: kafka
    environment:
      - "192.168.1.77"
    ports:
      - 9092:9092      
      - 2181:2181      

  cassandra:
    image: bigdatagrapes/cassandra:v1
    container_name: cassandra
    environment:
      - "192.168.1.77"
    ports:
      - 7100:7199
    
      
  kibana:
    image: bigdatagrapes/kibana
    container_name: kibana
    environment:
      - "192.168.1.77"
    ports:
      - 2122:2122
      - 8030:8030    
      - 8040:8040    
      - 8042:8042    
      - 8088:8088    
      - 19888:19888    
      - 49707:49707    
      - 50010:50010    
      - 50020:50020    
      - 50070:50070    
      - 50075:50075    
      - 50090:50090    
      
  phpmyadmin:
    image: bigdatagrapes/phpmyadmin
    container_name: phpmyadmin
    environment:
      - "192.168.1.77"
    ports:
      - 9000:9000
      
  mysql:
    image: bigdatagrapes/mysql
    container_name: mysql
    environment:
      - "192.168.1.77"
    ports:
      - 3306:3306
      - 33060:33060
      
  tomcat:
    image: bigdatagrapes/tomcat
    container_name: tomcat
    environment:
      - "192.168.1.77"
    ports:
      - 8888:8888
      
  logstash:
    image: bigdatagrapes/logstash
    container_name: logstash
    environment:
      - "192.168.1.77"
    ports:
      - 8700:9000
  
  graphdb:
    image: bigdatagrapes/graphdb
    container_name: graphdb
    environment:
      - "192.168.1.77"      
    ports:
      - 7200:7200

  flume:
    image: bde2020/flume
    container_name: flume
    environment:
      - "192.168.1.77"      
    