version: '3.3'
services:
  elasticsearch:
    image: bigdatagrapes/elasticsearch
    container_name: elasticsearch
    environment:
      - "127.0.0.1"
    ports:
      - 9200:9200
      - 9300:9300  
      
  hadoop:
    image: bigdatagrapes/hadoop
    container_name: hadoop
    environment:
      - "127.0.0.1"
    ports:
      - 5601:5601

  virtuoso:
    image: bigdatagrapes/virtuoso
    container_name: virtuoso
    environment:
      - "127.0.0.1"
    ports:
      - 5001:5609
  neo4j:
    image: bigdatagrapes/neo4j
    container_name: neo4j
    environment:
      - "127.0.0.1"
    ports:
      - 3001:3609
  hbase:
    image: bigdatagrapes/hbase
    container_name: hbase
    environment:
      - "127.0.0.1"
    ports:
      - 16000:16000
      - 16010:16010

      
  flink:
    image: bigdatagrapes/flink
    container_name: flink
    environment:
      - "127.0.0.1"
    ports:
      - 6123:6123
      - 8089:8089

  spark-master:
    image: bigdatagrapes/spark-master
    container_name: spark-master
    environment:
      - "127.0.0.1"
    ports:
      - 8080:8080
      - 6066:6066
      - 7077:7077

  spark-worker:
    image: bigdatagrapes/spark-worker
    container_name: spark-worker
    environment:
      - "127.0.0.1"
    ports:
      - 8081:8081

  mongo:
    image: bigdatagrapes/mongo
    container_name: mongo
    environment:
      - "127.0.0.1"
    ports:
      - 27017:27017

  sparklingwater:
    image: bigdatagrapes/sparklingwater
    container_name: sparklingwater
    environment:
      - "127.0.0.1"
    ports:
      - 27000:27017
      
  kafka:
    image: bigdatagrapes/kafka
    container_name: kafka
    environment:
      - "127.0.0.1"
    ports:
      - 9092:9092      
      - 2181:2181      

  cassandra:
    image: bigdatagrapes/cassandra:v1
    container_name: cassandra
    environment:
      - "127.0.0.1"
    ports:
      - 7100:7199
    
      
  kibana:
    image: bigdatagrapes/kibana
    container_name: kibana
    environment:
      - "127.0.0.1"
    ports:
      - 2122:3122
   
      
  phpmyadmin:
    image: bigdatagrapes/phpmyadmin
    container_name: phpmyadmin
    environment:
      - "127.0.0.1"
    ports:
      - 9000:9000
      
  mysql:
    image: bigdatagrapes/mysql
    container_name: mysql
    environment:
      - "127.0.0.1"
    ports:
      - 3307:3310
      - 33060:33060
      
  tomcat:
    image: bigdatagrapes/tomcat
    container_name: tomcat
    environment:
      - "127.0.0.1"
    ports:
      - 8888:8888
      
  logstash:
    image: bigdatagrapes/logstash
    container_name: logstash
    environment:
      - "127.0.0.1"
    ports:
      - 8700:9000
  
  graphdb:
    image: bigdatagrapes/graphdb
    container_name: graphdb
    environment:
      - "127.0.0.1"      
    ports:
      - 7200:7200

  flume:
    image: bigdatagrapes/flume
    container_name: flume
    environment:
      - "127.0.0.1"      
    ports:
      - 8020:9000

  predictive-data-analytics:
    image: bigdatagrapes/predictive-data-analytics:v1
    container_name: predictive-data-analytics
    environment:
      - "127.0.0.1"
    ports:
      - 5000:5010
